'use strict';
const crypto=require('node:crypto');
const {HttpError,playerName}=require('./mp-security.cjs');
const {currentRound,roundWindow}=require('./periods.cjs');
const {getTrack,publicTracks}=require('./race-tracks.js');

const MIN_PLAYERS=2,MAX_PLAYERS=8,QUEUE_WAIT_MS=12000,QUEUE_STALE_MS=120000,START_DELAY_MS=5000,RACE_SECONDS=110,COUNTED_RACES=30;
const BASE_POINTS=[25,18,15,12,10,8,6,4];
const COLORS=['#f4c542','#ff7043','#ef5350','#ec407a','#ab47bc','#7e57c2','#5c6bc0','#42a5f5','#26c6da','#26a69a','#66bb6a','#d4e157','#ffffff','#b0bec5'];
function playerColor(value){const v=String(value||'').toLowerCase();const found=COLORS.find(c=>c.toLowerCase()===v);return found||COLORS[0];}
function scaledPoints(place,count){const base=BASE_POINTS[place-1]||0;return base?Math.max(1,Math.round(base*Math.min(MAX_PLAYERS,count)/MAX_PLAYERS)):0;}
function addColumn(db,table,name,type){const cols=new Set(db.prepare(`PRAGMA table_info(${table})`).all().map(c=>c.name));if(!cols.has(name))db.exec(`ALTER TABLE ${table} ADD COLUMN ${name} ${type}`);}

function ensureMultiplayerSchema(db){
  db.exec(`
    CREATE TABLE IF NOT EXISTS multiplayer_players(session TEXT PRIMARY KEY,name TEXT NOT NULL,color TEXT NOT NULL DEFAULT '#f4c542',created INTEGER NOT NULL,last_seen INTEGER NOT NULL);
    CREATE TABLE IF NOT EXISTS multiplayer_queue(session TEXT PRIMARY KEY,name TEXT NOT NULL,color TEXT NOT NULL DEFAULT '#f4c542',joined INTEGER NOT NULL,last_seen INTEGER NOT NULL);
    CREATE INDEX IF NOT EXISTS multiplayer_queue_joined ON multiplayer_queue(joined,last_seen);
    CREATE TABLE IF NOT EXISTS multiplayer_matches(id TEXT PRIMARY KEY,seed INTEGER NOT NULL,track_id TEXT NOT NULL DEFAULT 'summit-smash',round INTEGER NOT NULL,engine TEXT NOT NULL,status TEXT NOT NULL,created INTEGER NOT NULL,start_at INTEGER NOT NULL,finish_deadline INTEGER NOT NULL,max_ticks INTEGER NOT NULL,server_tick INTEGER NOT NULL DEFAULT 0,finalized INTEGER,replay_id TEXT);
    CREATE INDEX IF NOT EXISTS multiplayer_matches_round ON multiplayer_matches(round,finalized);
    CREATE TABLE IF NOT EXISTS multiplayer_match_players(match_id TEXT NOT NULL,session TEXT NOT NULL,name TEXT NOT NULL,color TEXT NOT NULL DEFAULT '#f4c542',seat INTEGER NOT NULL,last_seen INTEGER NOT NULL,connected INTEGER NOT NULL DEFAULT 1,finish_ms INTEGER,score INTEGER,distance INTEGER,coins INTEGER,shots INTEGER NOT NULL DEFAULT 0,hits INTEGER NOT NULL DEFAULT 0,respawns INTEGER NOT NULL DEFAULT 0,forfeited INTEGER NOT NULL DEFAULT 0,placement INTEGER,points INTEGER,inputs TEXT,PRIMARY KEY(match_id,session),UNIQUE(match_id,seat),FOREIGN KEY(match_id) REFERENCES multiplayer_matches(id) ON DELETE CASCADE);
    CREATE INDEX IF NOT EXISTS multiplayer_results_session ON multiplayer_match_players(session,match_id);
    CREATE INDEX IF NOT EXISTS multiplayer_results_match ON multiplayer_match_players(match_id,placement);
    CREATE TABLE IF NOT EXISTS mp_lobbies(code TEXT PRIMARY KEY,host_session TEXT NOT NULL,created INTEGER NOT NULL,updated INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'open');
    CREATE TABLE IF NOT EXISTS mp_lobby_players(code TEXT NOT NULL,session TEXT UNIQUE NOT NULL,name TEXT NOT NULL,color TEXT NOT NULL,joined INTEGER NOT NULL,PRIMARY KEY(code,session),FOREIGN KEY(code) REFERENCES mp_lobbies(code) ON DELETE CASCADE);
    CREATE INDEX IF NOT EXISTS mp_lobby_players_code ON mp_lobby_players(code,joined);
    CREATE TABLE IF NOT EXISTS multiplayer_replays(public_id TEXT PRIMARY KEY,match_id TEXT UNIQUE NOT NULL,track_id TEXT NOT NULL,created INTEGER NOT NULL,data TEXT NOT NULL,FOREIGN KEY(match_id) REFERENCES multiplayer_matches(id) ON DELETE CASCADE);
  `);
  addColumn(db,'multiplayer_matches','race_type',"TEXT NOT NULL DEFAULT 'public'");
  // Safe upgrades from multiplayer v1.
  addColumn(db,'multiplayer_players','color',"TEXT NOT NULL DEFAULT '#f4c542'");
  addColumn(db,'multiplayer_queue','color',"TEXT NOT NULL DEFAULT '#f4c542'");
  for(const [name,type] of [['track_id',"TEXT NOT NULL DEFAULT 'summit-smash'"],['server_tick','INTEGER NOT NULL DEFAULT 0'],['replay_id','TEXT']])addColumn(db,'multiplayer_matches',name,type);
  for(const [name,type] of [['color',"TEXT NOT NULL DEFAULT '#f4c542'"],['connected','INTEGER NOT NULL DEFAULT 1'],['finish_ms','INTEGER'],['last_seq','INTEGER NOT NULL DEFAULT -1'],['shots','INTEGER NOT NULL DEFAULT 0'],['hits','INTEGER NOT NULL DEFAULT 0'],['respawns','INTEGER NOT NULL DEFAULT 0']])addColumn(db,'multiplayer_match_players',name,type);
}

function createMultiplayer(db,{now=Date.now,engineVersion='race-web-1'}={}){
  ensureMultiplayerSchema(db);
  function cleanup(){const t=now();db.prepare('DELETE FROM multiplayer_queue WHERE last_seen<?').run(t-QUEUE_STALE_MS);db.prepare('DELETE FROM multiplayer_replays WHERE created<?').run(t-90*86400000);db.prepare("DELETE FROM mp_lobbies WHERE updated<? OR status!='open'").run(t-2*3600000);db.prepare(`UPDATE multiplayer_match_players SET inputs=NULL WHERE match_id IN (SELECT id FROM multiplayer_matches WHERE finalized IS NOT NULL AND finalized<?)`).run(t-30*86400000);}
  function touchPlayer(session,rawName,rawColor){const name=playerName(rawName),color=playerColor(rawColor),t=now();db.prepare(`INSERT INTO multiplayer_players(session,name,color,created,last_seen)VALUES(?,?,?,?,?) ON CONFLICT(session) DO UPDATE SET name=excluded.name,color=excluded.color,last_seen=excluded.last_seen`).run(session,name,color,t,t);return{name,color};}
  function joinQueue(session,rawName,rawColor){cleanup();leaveLobby(session);const p=touchPlayer(session,rawName,rawColor),t=now();const active=getActiveMatch(session);if(active)return{active:true,matchId:active.id,player:p};db.prepare(`INSERT INTO multiplayer_queue(session,name,color,joined,last_seen)VALUES(?,?,?,?,?) ON CONFLICT(session) DO UPDATE SET name=excluded.name,color=excluded.color,last_seen=excluded.last_seen`).run(session,p.name,p.color,t,t);return{active:false,queue:queueState(session),player:p};}
  function leaveQueue(session){db.prepare('DELETE FROM multiplayer_queue WHERE session=?').run(session);return{ok:true};}
  function touchQueue(session){db.prepare('UPDATE multiplayer_queue SET last_seen=? WHERE session=?').run(now(),session);}
  function queueState(session){cleanup();const own=db.prepare('SELECT * FROM multiplayer_queue WHERE session=?').get(session);if(!own)return null;const size=db.prepare('SELECT COUNT(*) n FROM multiplayer_queue').get().n;const position=db.prepare('SELECT COUNT(*) n FROM multiplayer_queue WHERE joined<? OR (joined=? AND session<=?)').get(own.joined,own.joined,own.session).n;return{size,position,joinedAt:own.joined,waitMs:Math.max(0,now()-own.joined),minPlayers:MIN_PLAYERS,maxPlayers:MAX_PLAYERS,startAfterMs:QUEUE_WAIT_MS};}
  function queued(limit=MAX_PLAYERS){cleanup();return db.prepare('SELECT * FROM multiplayer_queue ORDER BY joined ASC,session ASC LIMIT ?').all(limit);}
  function removeQueued(sessions){const stmt=db.prepare('DELETE FROM multiplayer_queue WHERE session=?');for(const s of sessions)stmt.run(s);}
  function getActiveMatch(session){return db.prepare(`SELECT m.* FROM multiplayer_matches m JOIN multiplayer_match_players p ON p.match_id=m.id WHERE p.session=? AND m.finalized IS NULL ORDER BY m.created DESC LIMIT 1`).get(session)||null;}
  function createMatch(players,trackId,startAt=now()+START_DELAY_MS,mode='public'){if(players.length<MIN_PLAYERS||players.length>MAX_PLAYERS)throw new Error('Invalid race size');const track=getTrack(trackId),id=crypto.randomUUID(),t=now(),round=currentRound(t),maxTicks=RACE_SECONDS*60;db.exec('BEGIN IMMEDIATE');try{db.prepare('INSERT INTO multiplayer_matches(id,seed,track_id,round,engine,status,created,start_at,finish_deadline,max_ticks,race_type)VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,crypto.randomInt(1,0x7fffffff),track.id,round,engineVersion,'countdown',t,startAt,startAt+RACE_SECONDS*1000+15000,maxTicks,mode);const ins=db.prepare('INSERT INTO multiplayer_match_players(match_id,session,name,color,seat,last_seen)VALUES(?,?,?,?,?,?)');players.forEach((p,i)=>ins.run(id,p.session,p.name,playerColor(p.color),i+1,t));removeQueued(players.map(p=>p.session));db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return db.prepare('SELECT * FROM multiplayer_matches WHERE id=?').get(id);}
  function matchRows(matchId){return db.prepare('SELECT * FROM multiplayer_match_players WHERE match_id=? ORDER BY seat').all(matchId);}
  function match(matchId){return db.prepare('SELECT * FROM multiplayer_matches WHERE id=?').get(matchId)||null;}
  function setConnected(matchId,session,connected){db.prepare('UPDATE multiplayer_match_players SET connected=?,last_seen=? WHERE match_id=? AND session=?').run(connected?1:0,now(),matchId,session);}
  function persistInputs(matchId,session,inputs,lastSeq=-1){db.prepare('UPDATE multiplayer_match_players SET inputs=?,last_seq=?,last_seen=? WHERE match_id=? AND session=?').run(JSON.stringify(inputs),lastSeq,now(),matchId,session);}
  function persistRace(matchId,tick,status,players){db.exec('BEGIN IMMEDIATE');try{setTick(matchId,tick,status);for(const p of players){persistInputs(matchId,p.session,p.inputs,p.lastSeq);setConnected(matchId,p.session,p.connected);}db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}
  function setTick(matchId,tick,status){db.prepare('UPDATE multiplayer_matches SET server_tick=?,status=? WHERE id=? AND finalized IS NULL').run(tick,status,matchId);}
  function savePlayerResult(matchId,session,result){db.prepare(`UPDATE multiplayer_match_players SET finish_ms=?,score=?,distance=?,coins=?,shots=?,hits=?,respawns=?,forfeited=?,last_seen=? WHERE match_id=? AND session=?`).run(result.finishMs??null,result.score||0,result.distance||0,result.coins||0,result.shots||0,result.hits||0,result.respawns||0,result.forfeited?1:0,now(),matchId,session);}
  function finalize(matchId,ordered,replayFrames){let m=match(matchId);if(!m)throw new HttpError(404,'Race not found.');if(m.finalized!==null)return m;const t=now(),rows=matchRows(matchId),bySession=new Map(rows.map(r=>[r.session,r]));db.exec('BEGIN IMMEDIATE');try{const update=db.prepare('UPDATE multiplayer_match_players SET placement=?,points=?,forfeited=? WHERE match_id=? AND session=?');ordered.forEach((o,i)=>{const row=bySession.get(o.session);if(!row)return;update.run(i+1,o.forfeited||m.race_type==='bots'?0:scaledPoints(i+1,rows.length),o.forfeited?1:0,matchId,o.session);});let replayId=null;if(Array.isArray(replayFrames)&&replayFrames.length){replayId=crypto.randomBytes(9).toString('base64url');db.prepare('INSERT INTO multiplayer_replays(public_id,match_id,track_id,created,data)VALUES(?,?,?,?,?)').run(replayId,matchId,m.track_id,t,JSON.stringify(replayFrames));}db.prepare("UPDATE multiplayer_matches SET status='finished',finalized=?,replay_id=? WHERE id=? AND finalized IS NULL").run(t,replayId,matchId);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}return match(matchId);}
  function publicMatch(matchId,session){const m=match(matchId);if(!m)return null;const rows=matchRows(matchId).sort((a,b)=>m.finalized!==null?(a.placement??99)-(b.placement??99):a.seat-b.seat);return{id:m.id,mode:m.race_type||'public',trackId:m.track_id,trackName:getTrack(m.track_id).name,status:m.status,startAt:m.start_at,finishDeadline:m.finish_deadline,serverTick:m.server_tick,finalizedAt:m.finalized,replayId:m.replay_id,replayUrl:m.replay_id?'/mp/replay/'+m.replay_id:null,playerCount:rows.length,players:rows.map(r=>({session:r.session===session?'you':undefined,name:r.name,color:r.color,seat:r.seat,bot:r.session.startsWith('bot:'),you:r.session===session,connected:Boolean(r.connected),finishMs:r.finish_ms,score:r.score,distance:r.distance,coins:r.coins,shots:r.shots,hits:r.hits,respawns:r.respawns,forfeited:Boolean(r.forfeited),placement:r.placement,points:r.points})),...(m.finalized!==null?{stats:lifetimeStats(session)}:{})};}
  function weeklyEntries(round=currentRound(now())){const rows=db.prepare(`SELECT p.*,m.round FROM multiplayer_match_players p JOIN multiplayer_matches m ON m.id=p.match_id WHERE m.round=? AND m.race_type<>'bots' AND p.session NOT LIKE 'bot:%' AND m.finalized IS NOT NULL AND p.placement IS NOT NULL ORDER BY m.finalized ASC,p.seat ASC`).all(round);const map=new Map();for(const r of rows){let x=map.get(r.session);if(!x){x={session:r.session,name:r.name,color:r.color,races:0,wins:0,seconds:0,thirds:0,podiums:0,points:[],bestScore:0,totalCoins:0,placeSum:0};map.set(r.session,x);}x.name=r.name;x.color=r.color;x.races++;if(r.forfeited)continue;x.wins+=r.placement===1?1:0;x.seconds+=r.placement===2?1:0;x.thirds+=r.placement===3?1:0;x.podiums+=r.placement<=3?1:0;x.points.push(r.points||0);x.bestScore=Math.max(x.bestScore,r.score||0);x.totalCoins+=r.coins||0;x.placeSum+=r.placement||0;}for(const x of map.values()){x.points.sort((a,b)=>b-a);x.countedRaces=Math.min(COUNTED_RACES,x.points.length);x.weeklyPoints=x.points.slice(0,COUNTED_RACES).reduce((a,b)=>a+b,0);x.averageFinish=x.races?Number((x.placeSum/x.races).toFixed(2)):null;x.countedLimit=COUNTED_RACES;}return[...map.values()].sort((a,b)=>b.weeklyPoints-a.weeklyPoints||b.wins-a.wins||a.averageFinish-b.averageFinish||a.name.localeCompare(b.name));}
  function lifetimeStats(session){const rows=db.prepare(`SELECT p.* FROM multiplayer_match_players p JOIN multiplayer_matches m ON m.id=p.match_id WHERE p.session=? AND m.race_type<>'bots' AND m.finalized IS NOT NULL ORDER BY m.finalized ASC`).all(session);let races=0,wins=0,seconds=0,thirds=0,podiums=0,dnfs=0,lifetimePoints=0,bestScore=0,totalCoins=0,totalShots=0,totalHits=0,totalRespawns=0,placeSum=0,streak=0,bestWinStreak=0;for(const r of rows){races++;if(r.forfeited){dnfs++;streak=0;continue;}wins+=r.placement===1?1:0;seconds+=r.placement===2?1:0;thirds+=r.placement===3?1:0;podiums+=r.placement<=3?1:0;lifetimePoints+=r.points||0;bestScore=Math.max(bestScore,r.score||0);totalCoins+=r.coins||0;totalShots+=r.shots||0;totalHits+=r.hits||0;totalRespawns+=r.respawns||0;placeSum+=r.placement||0;if(r.placement===1){streak++;bestWinStreak=Math.max(bestWinStreak,streak);}else streak=0;}let currentWinStreak=0;for(let i=rows.length-1;i>=0;i--){if(rows[i].forfeited||rows[i].placement!==1)break;currentWinStreak++;}const week=weeklyEntries().find(x=>x.session===session);return{races,wins,seconds,thirds,podiums,dnfs,lifetimePoints,bestScore,totalCoins,totalShots,totalHits,totalRespawns,currentWinStreak,bestWinStreak,averageFinish:races?Number((placeSum/races).toFixed(2)):null,winRate:races?Number((wins/races*100).toFixed(1)):0,podiumRate:races?Number((podiums/races*100).toFixed(1)):0,weekly:week?{weeklyPoints:week.weeklyPoints,races:week.races,wins:week.wins,podiums:week.podiums,countedRaces:week.countedRaces,countedLimit:COUNTED_RACES}:{weeklyPoints:0,races:0,wins:0,podiums:0,countedRaces:0,countedLimit:COUNTED_RACES}};}
  function profile(session){const p=db.prepare('SELECT name,color,created,last_seen FROM multiplayer_players WHERE session=?').get(session)||null;return{name:p?.name||null,color:p?.color||COLORS[0],createdAt:p?.created||null,stats:lifetimeStats(session),colors:COLORS,tracks:publicTracks()};}
  function lobbyBySession(session){return db.prepare(`SELECT l.* FROM mp_lobbies l JOIN mp_lobby_players p ON p.code=l.code WHERE p.session=? AND l.status='open'`).get(session)||null;}
  function lobbyMembers(code){return db.prepare('SELECT * FROM mp_lobby_players WHERE code=? ORDER BY joined,session').all(code);}
  function lobbyState(session){const lobby=lobbyBySession(session);if(!lobby)return null;return{code:lobby.code,host:lobby.host_session===session,playerCount:lobbyMembers(lobby.code).length,maxPlayers:MAX_PLAYERS,players:lobbyMembers(lobby.code).map(p=>({name:p.name,color:p.color,you:p.session===session,host:p.session===lobby.host_session})),shareCode:lobby.code};}
  function leaveLobby(session){const lobby=lobbyBySession(session);if(!lobby)return null;db.prepare('DELETE FROM mp_lobby_players WHERE session=?').run(session);const rest=lobbyMembers(lobby.code);if(!rest.length)db.prepare('DELETE FROM mp_lobbies WHERE code=?').run(lobby.code);else if(lobby.host_session===session)db.prepare('UPDATE mp_lobbies SET host_session=?,updated=? WHERE code=?').run(rest[0].session,now(),lobby.code);return lobby.code;}
  function createLobby(session,name,color){if(getActiveMatch(session))throw new HttpError(409,'Finish your active race first.');const p=touchPlayer(session,name,color);leaveQueue(session);leaveLobby(session);let code;for(let i=0;i<10;i++){code=crypto.randomBytes(5).toString('hex').toUpperCase();if(!db.prepare('SELECT 1 FROM mp_lobbies WHERE code=?').get(code))break;}const t=now();db.prepare('INSERT INTO mp_lobbies(code,host_session,created,updated,status)VALUES(?,?,?,?,?)').run(code,session,t,t,'open');db.prepare('INSERT INTO mp_lobby_players(code,session,name,color,joined)VALUES(?,?,?,?,?)').run(code,session,p.name,p.color,t);return lobbyState(session);}
  function joinLobby(session,rawCode,name,color){const code=String(rawCode||'').trim().toUpperCase();if(!/^[A-F0-9]{10}$/.test(code))throw new HttpError(400,'Invalid friend-room code.');const lobby=db.prepare("SELECT * FROM mp_lobbies WHERE code=? AND status='open'").get(code);if(!lobby)throw new HttpError(404,'Friend room has expired or already started.');if(getActiveMatch(session))throw new HttpError(409,'Finish your active race first.');const existing=lobbyBySession(session);if(existing?.code!==code&&lobbyMembers(code).length>=MAX_PLAYERS)throw new HttpError(409,'This room is full.');const p=touchPlayer(session,name,color);leaveQueue(session);if(existing?.code!==code)leaveLobby(session);const t=now();db.prepare('INSERT INTO mp_lobby_players(code,session,name,color,joined)VALUES(?,?,?,?,?) ON CONFLICT(session) DO UPDATE SET name=excluded.name,color=excluded.color').run(code,session,p.name,p.color,t);db.prepare('UPDATE mp_lobbies SET updated=? WHERE code=?').run(t,code);return lobbyState(session);}
  function startLobby(session,withBots=false){const lobby=lobbyBySession(session);if(!lobby)throw new HttpError(404,'Friend room not found.');if(lobby.host_session!==session)throw new HttpError(403,'Only the host can start a race.');const players=lobbyMembers(lobby.code);if(players.length<MIN_PLAYERS&&!withBots)throw new HttpError(409,'Wait for another player or choose Fill with bots.');if(withBots){let n=1;while(players.length<4){players.push({session:'bot:'+crypto.randomBytes(9).toString('hex'),name:'BOT '+n,color:COLORS[(n*3)%COLORS.length],joined:now()});n++;}}db.prepare('DELETE FROM mp_lobbies WHERE code=?').run(lobby.code);return{players,hasBots:players.some(p=>p.session.startsWith('bot:'))};}
  function botPlayers(session,name,color,count=3){if(getActiveMatch(session))throw new HttpError(409,'Finish your active race first.');const p=touchPlayer(session,name,color);leaveQueue(session);leaveLobby(session);const n=Number(count);if(!Number.isInteger(n)||n<1||n>7)throw new HttpError(400,'Invalid bot count.');return[{session,name:p.name,color:p.color},...Array.from({length:n},(_,i)=>({session:'bot:'+crypto.randomBytes(9).toString('hex'),name:'BOT '+(i+1),color:COLORS[(i*3+4)%COLORS.length]}))];}
  function leaderboard(round=currentRound(now()),session=null){const w=roundWindow(round),entries=weeklyEntries(round).slice(0,50).map((e,i)=>({rank:i+1,name:e.name,color:e.color,weeklyPoints:e.weeklyPoints,races:e.races,wins:e.wins,podiums:e.podiums,countedRaces:e.countedRaces,countedLimit:e.countedLimit,averageFinish:e.averageFinish,you:session?e.session===session:false}));return{round,period:w.period,roundStarts:w.start,roundEnds:w.end,countedRaceLimit:COUNTED_RACES,entries,updatedAt:now()};}
  function lifetimeLeaderboard(session=null){
    const rows=db.prepare(`SELECT r.session,COALESCE(pro.name,MAX(r.name)) AS name,COALESCE(pro.color,MAX(r.color)) AS color,
      COUNT(*) races, SUM(CASE WHEN r.forfeited=0 AND r.placement=1 THEN 1 ELSE 0 END) wins,
      SUM(CASE WHEN r.forfeited=0 AND r.placement<=3 THEN 1 ELSE 0 END) podiums,
      COALESCE(SUM(r.points),0) lifetimePoints
      FROM multiplayer_match_players r JOIN multiplayer_matches m ON m.id=r.match_id
      LEFT JOIN multiplayer_players pro ON pro.session=r.session
      WHERE m.finalized IS NOT NULL AND m.race_type<>'bots' AND r.session NOT LIKE 'bot:%' GROUP BY r.session
      ORDER BY lifetimePoints DESC,wins DESC,races DESC,name ASC LIMIT 50`).all();
    return{type:'lifetime',entries:rows.map((e,i)=>({...e,rank:i+1,you:e.session===session})),updatedAt:now()};
  }
  function trackLeaderboard(trackId,session=null){
    const track=publicTracks().find(t=>t.id===trackId);if(!track)throw new HttpError(400,'Unknown track.');
    const rows=db.prepare(`SELECT r.session,COALESCE(pro.name,MAX(r.name)) AS name,COALESCE(pro.color,MAX(r.color)) AS color,
      COUNT(*) races, MIN(r.finish_ms) bestMs,
      SUM(CASE WHEN r.placement=1 THEN 1 ELSE 0 END) wins,
      SUM(CASE WHEN r.placement<=3 THEN 1 ELSE 0 END) podiums
      FROM multiplayer_match_players r JOIN multiplayer_matches m ON m.id=r.match_id
      LEFT JOIN multiplayer_players pro ON pro.session=r.session
      WHERE m.finalized IS NOT NULL AND m.race_type<>'bots' AND r.session NOT LIKE 'bot:%' AND m.track_id=? AND r.forfeited=0 AND r.finish_ms IS NOT NULL
      GROUP BY r.session ORDER BY bestMs ASC,wins DESC,name ASC LIMIT 50`).all(track.id);
    return{type:'track',trackId:track.id,trackName:track.name,entries:rows.map((e,i)=>({...e,rank:i+1,you:e.session===session})),updatedAt:now()};
  }
  function replay(publicId){const row=db.prepare('SELECT * FROM multiplayer_replays WHERE public_id=?').get(String(publicId||''));if(!row)return null;return{id:row.public_id,matchId:row.match_id,trackId:row.track_id,createdAt:row.created,frames:JSON.parse(row.data)};}
  function recoverableMatches(){return db.prepare('SELECT * FROM multiplayer_matches WHERE finalized IS NULL AND finish_deadline>? ORDER BY created').all(now()-15000);}
  function abandonExpired(){const expired=db.prepare('SELECT id FROM multiplayer_matches WHERE finalized IS NULL AND finish_deadline<?').all(now());for(const x of expired){const rows=matchRows(x.id).map(r=>({session:r.session,forfeited:true}));if(rows.length)finalize(x.id,rows,[]);}return expired.length;}
  return{createLobby,joinLobby,leaveLobby,lobbyState,lobbyMembers,startLobby,botPlayers,touchPlayer,joinQueue,leaveQueue,touchQueue,queueState,queued,removeQueued,getActiveMatch,createMatch,match,matchRows,setConnected,persistInputs,persistRace,setTick,savePlayerResult,finalize,publicMatch,leaderboard,lifetimeLeaderboard,trackLeaderboard,profile,replay,recoverableMatches,abandonExpired,constants:{MIN_PLAYERS,MAX_PLAYERS,QUEUE_WAIT_MS,QUEUE_STALE_MS,START_DELAY_MS,RACE_SECONDS,COUNTED_RACES,COLORS}};
}
module.exports={ensureMultiplayerSchema,createMultiplayer,scaledPoints,playerColor,MIN_PLAYERS,MAX_PLAYERS,QUEUE_WAIT_MS,START_DELAY_MS,RACE_SECONDS,COUNTED_RACES,COLORS};
